### ISSUE TITLE
xindy is not working

### ISSUE THREAD

**Issue by szarnyasg** [shuichiro-makigaki/docker-texlive-2020#1]
Hi,

Thanks for this Docker image, I'm a long-time user of it!

I have noticed that the `xindy` support does not work:
```bash
docker run --rm -i -t makisyu/texlive-2020 /bin/bash
[root@2e2b4c947421 /]# xindy --version
xindy release: 2.5.1
xindy script version: 1.18
/usr/local/texlive/2020/bin/x86_64-linux/xindy.run: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```

Installing the `ncurses-compat-libs` (as suggested on [Stack Exchange](https://tex.stackexchange.com/a/542418/71109)) package with `dnf` resolved the issue for me.

**Comment by shuichiro-makigaki** [comment]
Thank you for your comment. This issue has been fixed in 6f97782d as per your suggestion.
Now docker hub is building a new image, but it will take few hours.
